#!/bin/sh

if [ "$1" = 'admin' ]; then
    cd /app
    daphne config.asgi:application -b 0.0.0.0 -p 8000
elif [ "$1" = 'migrate' ]; then
    cd /app
    python manage.py migrate
else
    echo "Unknow argument $1"
    exit 1
fi
