# Generated by Django 2.1.7 on 2019-03-03 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('vat', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('zipcode', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=64)),
                ('alias', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftype', models.CharField(choices=[('hour', 'hour'), ('unit', 'unit'), ('total', 'total')], default='hour', max_length=8)),
                ('activity', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=32)),
                ('number', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('send', 'send'), ('received', 'received')], max_length=8)),
                ('currency', models.CharField(default='€', max_length=4)),
                ('tax', models.IntegerField(default=21)),
                ('taxname', models.CharField(default='IVA', max_length=16)),
                ('reverse_tax', models.IntegerField(default=15)),
                ('reverse_taxname', models.CharField(default='IRPF', max_length=16)),
                ('fees', models.ManyToManyField(related_name='invoices', to='ynvo.Fee')),
            ],
        ),
        migrations.CreateModel(
            name='Transmitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('vat', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('zipcode', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=64)),
                ('payment', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='invo_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ynvo.Transmitter'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invo_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ynvo.Client'),
        ),
    ]
