# Generated by Django 2.1.7 on 2019-03-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='prefix',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('send', 'send'), ('received', 'received')], default='created', max_length=8),
        ),
    ]
