# Generated by Django 2.1.7 on 2019-04-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvo', '0003_auto_20190304_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.CharField(default='', max_length=128),
        ),
    ]
