# Generated by Django 2.1.7 on 2019-04-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvo', '0004_invoice_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
