# Generated by Django 2.2.1 on 2019-07-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvo', '0006_auto_20190712_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
