# Generated by Django 2.2.3 on 2019-07-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvo', '0007_invoice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='proforma',
            field=models.BooleanField(default=False),
        ),
    ]
