# Generated by Django 2.2.3 on 2019-11-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvo', '0008_invoice_proforma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-number',)},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
