# Generated by Django 4.2.7 on 2023-12-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ynvo', '0009_auto_20191128_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='transmitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='ynvo.transmitter'),
        ),
    ]
