# Generated by Django 4.2.7 on 2023-12-05 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ynvo', '0012_fee_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='fees',
        ),
        migrations.AlterField(
            model_name='fee',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='ynvo.invoice'),
        ),
    ]
