# Generated by Django 4.2.7 on 2023-12-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvo', '0014_task_created_task_deadline_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'In progress'), ('F', 'Finished'), ('B', 'Blocked')], default='P', max_length=128),
        ),
        migrations.AlterField(
            model_name='task',
            name='branch',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
