# Generated by Django 5.2.12 on 2026-03-10 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_verifactu', '0001_initial'),
        ('ynvo', '0017_alter_client_id_alter_comment_id_alter_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_verifactu.invoicerecord'),
        ),
    ]
