# Generated by Django 5.2.12 on 2026-03-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvo', '0018_invoice_invoice_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_activity',
            field=models.CharField(blank=True, default='Trabajos realizados de mantenimiento y actualización del software', max_length=256),
        ),
        migrations.AddField(
            model_name='client',
            name='discount_description',
            field=models.CharField(blank=True, default='', help_text='Ej: por volumen de 500 horas', max_length=256),
        ),
        migrations.AddField(
            model_name='client',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='price_per_hour',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
