"""
Django settings for invoices project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from os import environ as env


def env_list(env_name, default=list):
    """Get environment var and convert in python list. Example .env: APPS=x1,y2,z3"""
    list_vars = env.get(env_name, None)
    return list_vars.split(",") if list_vars else default


def env_get_admins():
    """Example: Foo:foo@test.com,Bar:bar@test.com"""
    res = list()
    list_vars = env.get("ADMINS", "")
    admins = list_vars.split(",") if list_vars else list()
    for adm in admins:
        res.append(tuple(adm.split(":")))
    return res


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.get("SECRET_KEY", "example")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", [])

ADMINS = env_get_admins()
MANAGERS = ADMINS

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "mathfilters",
    "django_verifactu",
    "ynvo",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "invoices.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "invoices.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": env.get("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": env.get("DB_NAME", "db.sqlite3"),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "es-es"

TIME_ZONE = "Europe/Madrid"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = env.get("STATIC_URL", "static/")
STATIC_ROOT = env.get("STATIC_ROOT", "static/")
MEDIA_URL = env.get("MEDIA_URL", "media/")
MEDIA_ROOT = env.get("MEDIA_ROOT", "media/")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CSRF_COOKIE_SECURE = env.get("CSRF_COOKIE_SECURE", "True") == "True"
CSRF_COOKIE_SAMESITE = env.get("CSRF_COOKIE_SAMESITE", "strict")
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", [])

# EMAIL
SERVER_EMAIL = env.get("SERVER_EMAIL", "root@localhost")
EMAIL_BACKEND = env.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_USE_TLS = env.get("EMAIL_USE_TLS", "False") == "True"
EMAIL_USE_SSL = env.get("EMAIL_USE_SSL", "False") == "True"
EMAIL_HOST = env.get("EMAIL_HOST", "localhost")
EMAIL_PORT = env.get("EMAIL_PORT", 25)
EMAIL_HOST_USER = env.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env.get("EMAIL_HOST_PASSWORD", "")

# VeriFactu (Real Decreto 1007/2023) — No VeriFactu mode
# Software identification (included in the XML SistemaInformatico block)
VERIFACTU_ENVIRONMENT = env.get("VERIFACTU_ENV", "test")  # "test" | "production"
VERIFACTU_SOFTWARE_COMPANY = env.get("VERIFACTU_SOFTWARE_COMPANY", "")
VERIFACTU_SOFTWARE_NIF = env.get("VERIFACTU_SOFTWARE_NIF", "")
VERIFACTU_SOFTWARE_NAME = env.get("VERIFACTU_SOFTWARE_NAME", "ynvo")
VERIFACTU_SOFTWARE_VERSION = env.get("VERIFACTU_SOFTWARE_VERSION", "1.0")
# Certificate paths — only needed if switching to automatic AEAT submission
# VERIFACTU_CERT_PATH = env.get("VERIFACTU_CERT_PATH", "")
# VERIFACTU_CERT_KEY_PATH = env.get("VERIFACTU_CERT_KEY_PATH", "")
