# Generated by Django 5.2.12 on 2026-03-10 10:02

import verifactu.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_nif', models.CharField(max_length=32)),
                ('serial_number', models.CharField(max_length=64)),
                ('issue_date', models.DateField()),
                ('invoice_type', models.CharField(choices=[('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3'), ('R4', 'R4'), ('R5', 'R5')], default=verifactu.constants.InvoiceType['F1'], max_length=2)),
                ('operation_type', models.CharField(choices=[('alta', 'Alta'), ('anulacion', 'Anulación')], default='alta', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_breakdown', models.JSONField(default=list)),
                ('fingerprint', models.CharField(max_length=64)),
                ('previous_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('generation_timestamp', models.DateTimeField()),
                ('xml_content', models.TextField(blank=True, default='')),
                ('is_amendment', models.BooleanField(default=False)),
                ('prior_rejection', models.CharField(blank=True, default='', max_length=1)),
                ('no_prior_record', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('accepted_errors', 'Accepted with errors'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('csv_code', models.CharField(blank=True, default='', max_length=16)),
                ('aeat_response', models.TextField(blank=True, default='')),
                ('aeat_error_code', models.CharField(blank=True, default='', max_length=5)),
                ('aeat_error_description', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('qr_url', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['issuer_nif', 'serial_number'], name='django_veri_issuer__3faf18_idx'), models.Index(fields=['status'], name='django_veri_status_d1e5ef_idx')],
            },
        ),
    ]
